apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: adottato
type: Opaque
stringData:
  # variabili necessarie per il container postgres
  POSTGRES_DB: postgres_db
  POSTGRES_USER: app_user
  POSTGRES_PASSWORD: app_password

  # alias usati dai microservizi
  DB_USER: app_user
  DB_PASSWORD: app_password