apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: adottato
type: Opaque
stringData:
  # variabili richieste da RabbitMQ
  RABBITMQ_DEFAULT_USER: user
  RABBITMQ_DEFAULT_PASS: password

  # alias usati dai microservizi
  SPRING_RABBITMQ_USERNAME: user
  SPRING_RABBITMQ_PASSWORD: password