import { AuthProvider } from "@/context/AuthContext";
import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import { Separator } from "@/components/ui/separator";
import NavbarClient from "@/components/NavbarClient";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata = {
    title: "AdottaTO",
    description: "Generated by create next app",
    icons: {
        icon: "/favicon.ico",
    },
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="it">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider> {/* 👈 Wrappa tutto */}
            <NavbarClient />
            <Separator className="my-4" />
            {children}
        </AuthProvider>
        </body>
        </html>
    );
}
