server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        # Route con accesso pubblico
        - id: adoptionpost_route_public
          uri: http://adoptionpostservice:8080
          predicates:
            - Path=/get-list,/get-list-filtered,/get-by-id/**

        # Route con autorizzazione
        - id: adoptionpost_route_auth
          uri: http://adoptionpostservice:8080
          predicates:
            - Path=/create-adoption-post,/delete-by-id/**,/update-by-id/**,/get-my-owned-posts,/get-my-adopted-posts
          filters:
            - JwtUserIdHeaderFilter

        - id: savedsearch_route_auth
          uri: http://savedsearchservice:8080
          predicates:
            - Path=/get-my-saved-search,/delete-saved-search/**,/save-search
          filters:
            - JwtUserIdHeaderFilter
jwt:
  secret: ${JWT_SECRET}
