server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        # Route con accesso pubblico
        - id: adoptionpost_route_public
          uri: http://localhost:8081 #adoptionpost
          predicates:
            - Path=/get-list,/get-list-filtered,/get-by-id/**

        # Route con autorizzazione
        - id: adoptionpost_route_auth
          uri: http://localhost:8081 #adoptionpost
          predicates:
            - Path=/create-adoption-post,/delete-by-id/**,/update-by-id/**,/get-my-owned-posts,/get-my-adopted-posts
          filters:
            - JwtUserIdHeaderFilter
jwt:
  secret: una-chiave-segreta-molto-lunga123456789
