server:
  port: ${SERVER_PORT:8090}

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      forwarded:
        enabled: true
      routes:
        # ADOPTION POST SERVICE: public
        - id: adoptionpost_route_public
          uri: http://adoption-post-service:8081
          predicates:
            - Path=/adoption/get/**

        # ADOPTION POST SERVICE: private
        - id: adoptionpost_route_auth
          uri: http://adoption-post-service:8081
          predicates:
            - Path=/adoption/post/**,/adoption/my/**
          filters:
            - JwtUserIdHeaderFilter

        # SAVED SEARCH SERVICE: private
        - id: savedsearch_route_auth
          uri: http://saved-search-service:8084
          predicates:
            - Path=/search/**
          filters:
            - JwtUserIdHeaderFilter


        # USER SERVICE: private
        - id: user_route_auth
          uri: http://user-service:8083
          predicates:
            - Path=/user/my-profile/**
          filters:
            - JwtUserIdHeaderFilter

        # USER SERVICE: public
        - id: user_route_public
          uri: http://user-service:8083
          predicates:
            - Path=/auth/**,/user/get/**,/oauth2/**,/login/oauth2/**

        # CHAT SERVICE: private
        - id: chat_route_auth
          uri: http://chat-service:8082
          predicates:
            - Path=/chat/**
          filters:
            - JwtUserIdHeaderFilter

jwt:
  secret: ${JWT_SECRET}
