spring:
  application:
    name: userservice

  datasource:
    url: jdbc:postgresql://postgres-db_adottato:5432/postgres_db
    username: ${DB_USER:app_user}
    password: ${DB_PASSWORD:app_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: schema_user
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/google"

jwt:
  secret: ${JWT_SECRET}

server:
  port: ${SERVER_PORT:8083}
  forward-headers-strategy: framework
