spring:
  application:
    name: saved-search-service

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_db
    username: ${DB_USER:app_user}
    password: ${DB_PASSWORD:app_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: schema_saved_search
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  rabbitmq:
    host: localhost #locale
    port: 5672
    username: user
    password: password

app:
  rabbitmq:
    exchange: adottato.exchange
    queue: savedsearch.queue
    routingkey:
      new-post: post.new

server:
  port: 8084
