spring:
  application:
    name: chat-service

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_db
    username: app_user
    password: app_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: schema_chat
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

app:
  rabbitmq:
    exchange: adottato.exchange
    routingkey:
      chat-notification: chat.notification
      chat-request-accepted: chat.request.accepted

server:
  port: 8082
