apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: adottato
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: adottato/user-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: shared-config
            - secretRef:
                name: postgres-secret
            - secretRef:
                name: app-secret

