spring:
    application:
        name: auth-google-service

    datasource:
        url: jdbc:postgresql://postgres-db_adottato:5432/postgres_db
        username: ${DB_USER:app_user}
        password: ${DB_PASSWORD:app_password}
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                default_schema: schema_b
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true

    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_CLIENT_ID}
                        client-secret: ${GOOGLE_CLIENT_SECRET}

server:
    port: 8080
