apiVersion: v1
kind: Service
metadata:
  name: adoption-post-service
  namespace: adottato
spec:
  selector:
    app: adoption-post-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
