apiVersion: v1
kind: Service
metadata:
  name: email-service
  namespace: adottato
spec:
  selector:
    app: email-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: ClusterIP
