apiVersion: v1
kind: Service
metadata:
  name: postgres-db-adottato
  namespace: adottato
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
