apiVersion: v1
kind: Service
metadata:
  name: saved-search-service
  namespace: adottato
spec:
  selector:
    app: saved-search-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP
