spring:
  application:
    name: email-service

  rabbitmq:
    host: localhost #locale
    port: 5672
    username: user
    password: password

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

app:
  rabbitmq:
    exchange: ${RABBITMQ_ADOTTATO_EXCHANGE} #adottato.exchange
    routingkey:
      chat-notification: ${RABBITMQ_CHAT_ROUTING_KEY} #chat.notification
    queue: email.queue.chat

server:
  port: ${SERVER_PORT:8085}
