spring:
  application:
    name: email-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: adottato.taass@gmail.com
    password: pzgyrvtzuqyvfbgt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  rabbitmq:
    host: localhost #locale
    port: 5672
    username: user
    password: password

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

app:
  webclient:
    userservice: ${USER_SERVICE_URL} #http://user-service:8083
  rabbitmq:
    exchange: ${RABBITMQ_ADOTTATO_EXCHANGE} # adottato.exchange
    routingkey:
      chat-notification: ${RABBITMQ_CHAT_NOTIFICATION_ROUTING_KEY}        # chat.notification
      savedsearch-match: ${RABBITMQ_SAVED_SEARCH_ROUTING_KEY} # savedsearch.match
    queue:
      chat-notification: ${RABBITMQ_EMAIL_QUEUE_CHAT} # email.queue.chat
      savedsearch-match: ${RABBITMQ_EMAIL_QUEUE_SAVED_SEARCH} # email.queue.savedsearch

server:
  port: ${SERVER_PORT:8085}
